import type { AppInstallBlueprint } from "@/src/types/app-install-blueprint";

export const searchBoardBlueprint: AppInstallBlueprint = {
  id: "search-board",
  appKey: "search_board",
  displayName: "Search Board",
  description:
    "Executive search workspace: candidates, client shortlists, and shortlist line items in HubSpot.",
  version: "1.0.0",
  customObjects: [
    {
      objectKey: "candidate",
      schemaName: "search_board_candidate",
      singularLabel: "Candidate",
      pluralLabel: "Candidates",
      description: "Search Board candidate profile (custom object).",
      primaryDisplayProperty: "candidate_name",
      propertyGroup: { name: "candidate_information", label: "Candidate Information" },
      requiredProperties: [
        {
          name: "candidate_name",
          label: "Candidate name",
          valueType: "string",
          fieldType: "text",
          groupName: "candidate_information",
          required: true,
        },
        {
          name: "current_title",
          label: "Current title",
          valueType: "string",
          fieldType: "text",
          groupName: "candidate_information",
        },
        {
          name: "summary",
          label: "Summary",
          valueType: "string",
          fieldType: "textarea",
          groupName: "candidate_information",
        },
        {
          name: "location",
          label: "Location",
          valueType: "string",
          fieldType: "text",
          groupName: "candidate_information",
        },
        {
          name: "gender",
          label: "Gender",
          valueType: "string",
          fieldType: "text",
          groupName: "candidate_information",
        },
        {
          name: "status",
          label: "Status",
          valueType: "string",
          fieldType: "text",
          groupName: "candidate_information",
        },
      ],
    },
    {
      objectKey: "shortlist",
      schemaName: "search_board_shortlist",
      singularLabel: "Shortlist",
      pluralLabel: "Shortlists",
      description: "Client-facing shortlist container.",
      primaryDisplayProperty: "shortlist_name",
      propertyGroup: { name: "shortlist_information", label: "Shortlist Information" },
      requiredProperties: [
        {
          name: "shortlist_name",
          label: "Shortlist name",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_information",
          required: true,
        },
        {
          name: "client_name",
          label: "Client name",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_information",
        },
        {
          name: "role_title",
          label: "Role title",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_information",
        },
        {
          name: "consultant_name",
          label: "Consultant name",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_information",
        },
        {
          name: "status",
          label: "Status",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_information",
        },
        {
          name: "portal_link",
          label: "Portal link",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_information",
        },
        {
          name: "portal_expiry",
          label: "Portal expiry",
          valueType: "date",
          fieldType: "date",
          groupName: "shortlist_information",
        },
        {
          name: "internal_notes",
          label: "Internal notes",
          valueType: "string",
          fieldType: "textarea",
          groupName: "shortlist_information",
        },
      ],
    },
    {
      objectKey: "shortlist_entry",
      schemaName: "search_board_shortlist_entry",
      singularLabel: "Shortlist Entry",
      pluralLabel: "Shortlist Entries",
      description: "Joins a candidate to a shortlist with ranking and feedback.",
      primaryDisplayProperty: "entry_name",
      propertyGroup: {
        name: "shortlist_entry_information",
        label: "Shortlist Entry Information",
      },
      requiredProperties: [
        {
          name: "rank",
          label: "Rank",
          valueType: "number",
          fieldType: "number",
          groupName: "shortlist_entry_information",
          required: true,
        },
        {
          name: "shortlist_status",
          label: "Shortlist status",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_entry_information",
        },
        {
          name: "client_feedback",
          label: "Client feedback",
          valueType: "string",
          fieldType: "textarea",
          groupName: "shortlist_entry_information",
        },
        {
          name: "internal_notes",
          label: "Internal notes",
          valueType: "string",
          fieldType: "textarea",
          groupName: "shortlist_entry_information",
        },
        {
          name: "entry_name",
          label: "Entry name",
          valueType: "string",
          fieldType: "text",
          groupName: "shortlist_entry_information",
        },
      ],
    },
  ],
  associations: [
    {
      id: "candidate_company",
      description: "Candidate ↔ Company",
      from: { kind: "blueprint_custom", objectKey: "candidate" },
      to: { kind: "hubspot_standard", objectType: "companies" },
    },
    {
      id: "candidate_contact",
      description: "Candidate ↔ Contact",
      from: { kind: "blueprint_custom", objectKey: "candidate" },
      to: { kind: "hubspot_standard", objectType: "contacts" },
    },
    {
      id: "shortlist_company",
      description: "Shortlist ↔ Company",
      from: { kind: "blueprint_custom", objectKey: "shortlist" },
      to: { kind: "hubspot_standard", objectType: "companies" },
    },
    {
      id: "entry_candidate",
      description: "Shortlist Entry ↔ Candidate",
      from: { kind: "blueprint_custom", objectKey: "shortlist_entry" },
      to: { kind: "blueprint_custom", objectKey: "candidate" },
    },
    {
      id: "entry_shortlist",
      description: "Shortlist Entry ↔ Shortlist",
      from: { kind: "blueprint_custom", objectKey: "shortlist_entry" },
      to: { kind: "blueprint_custom", objectKey: "shortlist" },
    },
  ],
  setupTasks: [
    {
      id: "review-company-association-cardinality",
      title: "Review company association cardinality in HubSpot",
      description:
        "Confirm whether many-to-many or one-to-many fits your search workflow before running live install.",
      optional: true,
    },
    {
      id: "configure-pipeline-roles",
      title: "Align status picklists with internal stages",
      optional: true,
    },
  ],
  validationChecks: [
    {
      id: "private-app-token",
      description: "Private app access token is configured for this environment",
      severity: "blocking",
    },
    {
      id: "schema-api-reachable",
      description: "HubSpot custom schema API responds successfully",
      severity: "blocking",
    },
    {
      id: "no-destructive-mutation-in-dry-run",
      description: "Dry-run mode must not call create/update/delete HubSpot APIs",
      severity: "warning",
    },
  ],
  mappingKeys: [
    {
      key: "objects.candidate.objectTypeId",
      description: "HubSpot object type id for Candidate",
      valueKind: "hubspot_object_type_id",
      source: { type: "blueprint_object", objectKey: "candidate" },
    },
    {
      key: "objects.shortlist.objectTypeId",
      description: "HubSpot object type id for Shortlist",
      valueKind: "hubspot_object_type_id",
      source: { type: "blueprint_object", objectKey: "shortlist" },
    },
    {
      key: "objects.shortlist_entry.objectTypeId",
      description: "HubSpot object type id for Shortlist Entry",
      valueKind: "hubspot_object_type_id",
      source: { type: "blueprint_object", objectKey: "shortlist_entry" },
    },
    {
      key: "properties.candidate.candidate_name",
      description: "Property internal name for candidate display name",
      valueKind: "hubspot_property_name",
      source: { type: "blueprint_property", objectKey: "candidate", propertyName: "candidate_name" },
    },
    {
      key: "associations.candidate_company",
      description: "Candidate ↔ Company association type",
      valueKind: "hubspot_association_type_id",
      source: { type: "blueprint_association", associationId: "candidate_company" },
    },
    {
      key: "associations.candidate_contact",
      description: "Candidate ↔ Contact association type",
      valueKind: "hubspot_association_type_id",
      source: { type: "blueprint_association", associationId: "candidate_contact" },
    },
    {
      key: "associations.shortlist_company",
      description: "Shortlist ↔ Company association type",
      valueKind: "hubspot_association_type_id",
      source: { type: "blueprint_association", associationId: "shortlist_company" },
    },
    {
      key: "associations.entry_candidate",
      description: "Shortlist Entry ↔ Candidate association type",
      valueKind: "hubspot_association_type_id",
      source: { type: "blueprint_association", associationId: "entry_candidate" },
    },
    {
      key: "associations.entry_to_shortlist",
      description: "Association type between Shortlist Entry and Shortlist",
      valueKind: "hubspot_association_type_id",
      source: { type: "blueprint_association", associationId: "entry_shortlist" },
    },
  ],
};
